on: [push]
env:
  NAMESPACE: Boss
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # Add the JFrog CLI      
    - uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
    # Create the Docker image and collect the envioroment variable
    - run: |
        cd workshop-app
        docker build . --file Dockerfile --tag bateltest.jfrog.io/azure-workshop/aks 
        jfrog rt dp bateltest.jfrog.io/azure-workshop/aks azure-workshop
    # Set the target AKS cluster.    
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        allow-no-subscriptions: true
        cluster-name: JFrogAKS
        resource-group: JFrogWorkshopCluster
    # Deploy to our AKS        
    - uses: Azure/k8s-deploy@v1.3
      with:
        manifests: |
          deployment.yml
        images: |
          bateltest.jfrog.io/azure-workshop/aks
    - run: |
        jfrog rt dl artifacts/
        jfrog rt u aether artifacts/
        jfrog rt bce
        jfrog rt bp
